# Generated by Django 6.1 on 2026-09-05 — 프로젝트별 분석 제외 경로 (RFP 외 자체 개선)

import projects.exclude_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exclude_paths',
            field=models.JSONField(blank=True, default=list, validators=[projects.exclude_paths.validate_exclude_paths_field], verbose_name='분석 제외 경로'),
        ),
    ]
