# Generated by Django 6.1 on 2026-09-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accounts_user_email_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='이름'),
        ),
    ]
