"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 설정값은 코드가 아니라 .env에서 읽는다 (시크릿 커밋 금지 — CLAUDE.md 보안 규칙).
# 템플릿은 .env.example, 실제 값이 든 .env는 .gitignore로 제외된다.
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    """.env의 문자열 값을 bool로 변환한다. 인식 못 하는 값은 default."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
# 기본값을 두지 않는다 — .env가 없으면 예측 가능한 키로 조용히 기동되어
# 세션·토큰 위조가 가능해지므로, 즉시 실패(fail-fast)시킨다.
# docker-compose.yml의 ${VAR:?} 와 같은 원칙.
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# 키가 없을 때 디버그가 켜지지 않도록 기본값은 False (안전한 기본값).
DEBUG = _env_bool('DJANGO_DEBUG', default=False)

# DEBUG=False면 Django가 ALLOWED_HOSTS를 강제하므로 비어 있으면 모든 요청이 400이 된다.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 서드파티
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',  # 로그아웃 시 refresh 토큰 폐기

    # 프로젝트 앱 — 책임별 분리 (QLT-001)
    'accounts',   # 사용자 인증, 역할, 권한
    'projects',   # 분석 프로젝트 관리, 사용자 할당
    'analysis',   # 소스 업로드, Semgrep 실행, 상태 관리
    'catalog',    # KISA 진단 기준, 결과 저장·조회
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


# docker-compose.yml과 같은 POSTGRES_* 키를 공유한다 — Django 전용 키를 따로 두면
# 컨테이너와 앱이 서로 다른 값을 바라볼 수 있다 (DAR-001).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# 인증 (SFR-001, DAR-002)
# 이메일 로그인 커스텀 User. 첫 migrate 전에 지정해야 auth.User로 고정되지 않는다.
AUTH_USER_MODEL = 'accounts.User'


# 비밀번호 해시 (SEC-001)
# bcrypt를 1순위로 둔다 — 적응형(느린) 해시라 무차별 대입에 강하다.
# BCryptSHA256은 bcrypt의 72바이트 입력 제한을 우회하려 SHA256으로 전처리할 뿐,
# 실제 저장 강도는 bcrypt가 담당한다 (CLAUDE.md 보안 규칙에서 명시적으로 허용).
# 뒤의 Django 기본 해셔는 과거 방식으로 저장된 해시를 검증하기 위해 남긴다.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# DRF (SFR-002, SEC-002)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 기본은 차단. 엔드포인트를 공개하려면 명시적으로 AllowAny를 걸어야 하므로,
    # 권한 지정을 빠뜨려도 인증 없이 열리지 않는다 (SEC-002, SEC-004).
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # bcrypt는 오프라인 크래킹을 늦출 뿐, 온라인 자동 대입은 막지 못한다.
    # ScopedRateThrottle은 throttle_scope를 지정한 뷰에만 적용되므로
    # 전역으로 걸어도 다른 엔드포인트에 영향이 없다 (SEC-001 보완).
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
    },
}

# 참고: 기본 캐시는 프로세스별 LocMemCache라 워커가 여러 개면 제한이 워커 수만큼
# 느슨해진다. 운영 배포 시 Redis 등 공유 캐시로 교체해야 한다.

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # 갱신 때마다 새 refresh를 발급하고 이전 것을 폐기한다 — 유출된 토큰의 수명을 줄인다.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': SECRET_KEY,
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# 분석 작업 영역 (SEC-007)
# 업로드 zip·압축 해제된 소스는 여기 아래, 실행(run)별 격리 디렉토리에서만 다룬다.
# .gitignore의 `/media/` 규칙이 이 경로를 커밋에서 제외한다.
MEDIA_ROOT = BASE_DIR / 'media'
ANALYSIS_WORKSPACE_ROOT = MEDIA_ROOT / 'analysis_runs'

# zip 업로드·압축 해제 상한 (SEC-008 — zip bomb 기본 방어)
# 실제 분석 대상(수천~수만 파일 규모 자바 프로젝트 등)에 맞춰 .env로 조정한다. 값이 커져도
# 압축 해제 루프가 실제 기록 바이트를 세어 중단하고, 코드 조각 추출은 별도 2MB 파일 상한을
# 두므로 zip bomb 방어와 메모리 보호는 유지된다.
ANALYSIS_MAX_UPLOAD_SIZE = int(os.getenv('ANALYSIS_MAX_UPLOAD_MB', '200')) * 1024 * 1024
ANALYSIS_MAX_EXTRACTED_SIZE = int(os.getenv('ANALYSIS_MAX_EXTRACTED_MB', '500')) * 1024 * 1024
ANALYSIS_MAX_EXTRACTED_FILES = int(os.getenv('ANALYSIS_MAX_EXTRACTED_FILES', '20000'))

# 진단 기준 카탈로그 (SFR-012, SFR-013, DAR-007)
# 룰 디렉토리는 두 곳에서 쓰인다 — seed_catalog 커맨드가 매핑을 읽고, Semgrep이 분석에
# 사용한다. 두 곳이 다른 디렉토리를 보면 "카탈로그에는 구현됨인데 실제로는 안 돌아가는"
# 상태가 되므로 정의를 여기 하나로 둔다.
CATALOG_RULES_DIR = BASE_DIR / 'catalog' / 'rules'
CATALOG_SEED_FILE = BASE_DIR / 'catalog' / 'data' / 'kisa_rules.json'


# Semgrep 실행 (SFR-008~009, SEC-009)
# 공개 레지스트리(p/python)를 쓰지 않고 KISA 49개에 매핑된 자체 룰만 사용한다 —
# 레지스트리 룰은 KISA 항목 매핑이 없어 등급 근거가 없는 결과를 만들고, 오탐 통제도
# 불가능하다 (QLT-002, docs/decisions.md).
ANALYSIS_SEMGREP_CONFIG = str(CATALOG_RULES_DIR)
# 초 — 타임아웃 시 FAILED로 기록. 수천 파일 규모 프로젝트는 2분으로 부족해 .env로 조정한다.
ANALYSIS_SEMGREP_TIMEOUT = int(os.getenv('ANALYSIS_SEMGREP_TIMEOUT', '600'))

# 분석 대상 언어 파일 확장자. 카탈로그 룰이 다루는 언어(Python: .py, C: .c/.h,
# Java: .java, JavaScript/TypeScript: .js/.jsx/.ts/.tsx)와 맞춘다 — 다른 언어 룰을
# 추가하면 여기도 함께 갱신한다 (SFR-011, SFR-012, TST-008).
# 룰 YAML에서 동적으로 파생하지 않는 이유: analysis 앱이 catalog의 룰 파일을 읽으면
# 역방향 의존이 생긴다 (QLT-001).
ANALYSIS_SCAN_TARGET_SUFFIXES = ('.py', '.c', '.h', '.java', '.js', '.jsx', '.ts', '.tsx')


# 접근 로그 (RFP 요구 아님 — 열람 이력 추적용 자체 개선, docs/decisions.md 2026-09-01)
# 결과 열람(실행 상세·결과 목록·집계) 이력을 logs/access.log에 남긴다.
# 시각은 formatter의 asctime이 붙인다. .gitignore의 `/logs/` 규칙으로 커밋에서 제외.
ACCESS_LOG_DIR = BASE_DIR / 'logs'
ACCESS_LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'access': {
            'format': '{asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'access_file': {
            'class': 'logging.FileHandler',
            'filename': ACCESS_LOG_DIR / 'access.log',
            'encoding': 'utf-8',
            # 첫 기록 시점에 파일을 연다 — 파일을 열 수 없는 환경에서도 기동과
            # 요청 처리는 영향받지 않는다 (핸들러 오류는 logging 모듈이 삼킨다).
            'delay': True,
            'formatter': 'access',
        },
    },
    'loggers': {
        'access': {
            'handlers': ['access_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
