# Generated by Django 6.1 on 2026-08-27 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='작업 영역 ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('RUNNING', '실행중'), ('SUCCEEDED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=10, verbose_name='상태')),
                ('raw_result', models.JSONField(blank=True, null=True, verbose_name='분석 결과(원본)')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='실행 시작 일시')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '분석 실행',
                'verbose_name_plural': '분석 실행',
                'db_table': 'analysis_run',
                'ordering': ('-created_at',),
            },
        ),
    ]
