# Generated by Django 6.1 on 2026-09-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisrun',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': '분석 실행', 'verbose_name_plural': '분석 실행'},
        ),
    ]
