# Generated by Django 6.1 on 2026-09-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisrun_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='큐 등록 일시'),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('QUEUED', '대기열'), ('RUNNING', '실행중'), ('SUCCEEDED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=10, verbose_name='상태'),
        ),
    ]
