# Generated by Django 6.1 on 2026-08-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='KISA-IV-01 형식. 유형약어 + 절 내 순번.', max_length=32, unique=True, verbose_name='항목 코드')),
                ('name', models.CharField(max_length=200, verbose_name='항목명')),
                ('category', models.CharField(choices=[('IV', '입력데이터 검증 및 표현'), ('SF', '보안기능'), ('TS', '시간 및 상태'), ('EH', '에러처리'), ('CE', '코드오류'), ('EN', '캡슐화'), ('AA', 'API 오용')], max_length=2, verbose_name='유형')),
                ('severity', models.CharField(choices=[('HIGH', '높음'), ('MEDIUM', '보통'), ('LOW', '낮음')], help_text='KISA 유형 성격에 따라 개발자가 확정한 등급 (docs/decisions.md).', max_length=6, verbose_name='심각도')),
                ('severity_reason', models.TextField(blank=True, verbose_name='심각도 사유')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('semgrep_rule_ids', models.JSONField(blank=True, default=list, verbose_name='연결된 Semgrep 룰')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='부가정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '진단 기준',
                'verbose_name_plural': '진단 기준',
                'db_table': 'catalog_rule',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(blank=True, max_length=32, verbose_name='항목 코드(스냅샷)')),
                ('rule_name', models.CharField(blank=True, max_length=200, verbose_name='항목명(스냅샷)')),
                ('severity', models.CharField(choices=[('HIGH', '높음'), ('MEDIUM', '보통'), ('LOW', '낮음')], max_length=6, verbose_name='심각도')),
                ('semgrep_check_id', models.CharField(max_length=255, verbose_name='Semgrep 룰 id')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일 경로')),
                ('start_line', models.PositiveIntegerField(default=0, verbose_name='시작 줄')),
                ('end_line', models.PositiveIntegerField(default=0, verbose_name='끝 줄')),
                ('message', models.TextField(blank=True, verbose_name='메시지')),
                ('code_snippet', models.TextField(blank=True, verbose_name='코드 조각')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='부가정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='catalog.diagnosticrule', verbose_name='진단 기준')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='analysis.analysisrun', verbose_name='분석 실행')),
            ],
            options={
                'verbose_name': '진단 결과',
                'verbose_name_plural': '진단 결과',
                'db_table': 'catalog_finding',
                'ordering': ('file_path', 'start_line', 'id'),
                'indexes': [models.Index(fields=['run', 'severity'], name='catalog_finding_run_sev'), models.Index(fields=['run', 'rule'], name='catalog_finding_run_rule')],
            },
        ),
    ]
