# Generated by Django 6.1 on 2026-09-02 01:44

# 백필(RunPython)은 0003에 따로 둔다 — 같은 마이그레이션(단일 트랜잭션)에 두면
# 인덱스 생성(deferred SQL)이 백필 UPDATE 뒤로 밀려 PostgreSQL이
# "cannot CREATE INDEX ... pending trigger events"로 거부한다.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='fingerprint',
            field=models.CharField(db_index=True, default='', max_length=80, verbose_name='핑거프린트'),
        ),
    ]
