# Generated by Django 6.1 on 2026-09-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisrun_options'),
        ('catalog', '0003_backfill_fingerprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('OPEN', '미처리'), ('FALSE_POSITIVE', '오탐'), ('ACCEPTED', '수용')], db_index=True, default='OPEN', max_length=16, verbose_name='판정'),
        ),
        migrations.AddField(
            model_name='finding',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='판정 일시'),
        ),
        migrations.AddField(
            model_name='finding',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finding_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='판정자'),
        ),
        migrations.AddField(
            model_name='finding',
            name='status_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='판정 사유'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['run', 'status'], name='catalog_finding_run_status'),
        ),
    ]
